# fly.toml app configuration file generated for discord-server-bot on 2023-08-24T18:33:59+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "discord-server-bot"
primary_region = "mad"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]